import type { Metadata } from "next";
import { Playfair_Display, Montserrat } from "next/font/google";
import "./globals.css";

const playfairDisplay = Playfair_Display({
	variable: "--font-playfairDisplay",
	subsets: ["latin"],
});
const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Archetyp | Wirtualna Czytelnia",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`${montserrat.variable} ${playfairDisplay.variable} h-full antialiased scroll-smooth`}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
