export const navigationContent = [
	{ href: "#hero", label: "Home" },
	{ href: "#ksiazki", label: "Książki" },
	{
		href: "#o-nas",
		label: "O nas",
	},
];

export const headerContent = {
	headerTitle: "Twoja wirtualna czytelnia.",
	headerSubtitle: "Czytaj swoje ulubione książki bez limitów.",
	headerDescription: "Odkryj tysiące e-booków dostępnych 24/7",
	headerCta: "Rozpocznij czytanie",
};

export const booksContent = {
	booksTitle: "Odkryj nasz asortyment",
};

export const asideLinksMain = [
	{
		href: "/dashboard/home",
		label: "Strona główna",
		icon: '<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline>',
	},
	{
		href: "/dashboard/ksiazki",
		label: "Książki",
		icon: '<path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path>',
	},
	{
		href: "/dashboard/ulubione",
		label: "Ulubione",
		icon: '<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>',
	},
	{
		href: "/dashboard/czytam",
		label: "Czytam",
		icon: '<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>',
	},
	{
		href: "/dashboard/przeczytane",
		label: "Przeczytane",
		icon: '<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline>',
	},
	{
		href: "/dashboard/notatki",
		label: "Notatki",
		icon: '<path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect>',
	},
];

export const asideLinks = [
	{
		href: "/dashboard/ustawienia",
		label: "Ustawienia",
		icon: `<circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>`,
	},
];
export const books = [
	[
		{
			id: 1,
			title: "The Shadow of the Wind",
			author: "Carlos Ruiz Zafón",
			description:
				"Młody chłopiec odkrywa tajemniczą zapomnianą książkę i zaczyna obsesyjnie poszukiwać informacji o jej autorze.",
			pages: 487,
			genre: "Mystery",
			year: 2001,
			language: "English",
			cover: "/books/shadow-of-the-wind.jpg",
			rating: 4.6,
			isbn: "9780143034902",
			estimatedReadingTime: "8h 30min",
			isAvailable: true,
		},
		{
			id: 2,
			title: "The Night Circus",
			author: "Erin Morgenstern",
			description:
				"Tajemniczy cyrk pojawia się bez ostrzeżenia, otwierając się wyłącznie nocą i stając się areną niebezpiecznej magicznej rywalizacji.",
			pages: 387,
			genre: "Fantasy",
			year: 2011,
			language: "English",
			cover: "/books/night-circus.jpg",
			rating: 4.4,
			isbn: "9780385534635",
			estimatedReadingTime: "6h 45min",
			isAvailable: true,
		},
		{
			id: 3,
			title: "The Name of the Rose",
			author: "Umberto Eco",
			description:
				"Średniowieczny klasztor staje się miejscem serii tajemniczych śmierci, które próbuje rozwikłać franciszkański zakonnik wraz ze swoim uczniem.",
			pages: 536,
			genre: "Historical Mystery",
			year: 1980,
			language: "English",
			cover: "/books/name-of-the-rose.jpg",
			rating: 4.5,
			isbn: "9780544174220",
			estimatedReadingTime: "9h 20min",
			isAvailable: true,
		},
		{
			id: 4,
			title: "The Ocean at the End of the Lane",
			author: "Neil Gaiman",
			description:
				"Mężczyzna wraca do domu z dzieciństwa i zaczyna przypominać sobie dziwne wydarzenia zacierające granicę między wspomnieniami a fantazją.",
			pages: 181,
			genre: "Fantasy",
			year: 2013,
			language: "English",
			cover: "/books/ocean-at-the-end.jpg",
			rating: 4.3,
			isbn: "9780062459367",
			estimatedReadingTime: "3h 10min",
			isAvailable: true,
		},
		{
			id: 5,
			title: "The Book Thief",
			author: "Markus Zusak",
			description:
				"Wojenne Niemcy. Młoda dziewczyna odkrywa siłę słów, kradnąc książki i nawiązując niezwykłe przyjaźnie.",
			pages: 584,
			genre: "Historical Fiction",
			year: 2005,
			language: "English",
			cover: "/books/book-thief.jpg",
			rating: 4.7,
			isbn: "9780375842207",
			estimatedReadingTime: "10h 15min",
			isAvailable: true,
		},
		{
			id: 6,
			title: "Neverwhere",
			author: "Neil Gaiman",
			description:
				"Londyński biznesmen odkrywa ukryty świat pod ulicami miasta po tym, jak pomaga tajemniczej rannej kobiecie.",
			pages: 370,
			genre: "Fantasy",
			year: 1996,
			language: "English",
			cover: "/books/neverwhere.jpg",
			rating: 4.2,
			isbn: "9780380789016",
			estimatedReadingTime: "6h 20min",
			isAvailable: true,
		},
		{
			id: 7,
			title: "The Picture of Dorian Gray",
			author: "Oscar Wilde",
			description:
				"Piękny młody mężczyzna pozostaje fizycznie niezmieniony, podczas gdy tajemniczy portret odzwierciedla konsekwencje jego coraz bardziej niemoralnego życia.",
			pages: 254,
			genre: "Gothic Fiction",
			year: 1890,
			language: "English",
			cover: "/books/dorian-gray.jpg",
			rating: 4.5,
			isbn: "9780141439570",
			estimatedReadingTime: "4h 30min",
			isAvailable: true,
		},
		{
			id: 8,
			title: "Frankenstein",
			author: "Mary Shelley",
			description:
				"Naukowiec tworzy żywą istotę i musi zmierzyć się z konsekwencjami porzucenia własnego dzieła.",
			pages: 280,
			genre: "Gothic Fiction",
			year: 1818,
			language: "English",
			cover: "/books/frankenstein.jpg",
			rating: 4.4,
			isbn: "9780141439471",
			estimatedReadingTime: "4h 50min",
			isAvailable: true,
		},
		{
			id: 9,
			title: "The Little Prince",
			author: "Antoine de Saint-Exupéry",
			description:
				"Pilot uwięziony na pustyni spotyka tajemniczego młodego księcia, którego podróż skłania do refleksji nad miłością, przyjaźnią i ludzką naturą.",
			pages: 96,
			genre: "Philosophical Fiction",
			year: 1943,
			language: "English",
			cover: "/books/little-prince.jpg",
			rating: 4.8,
			isbn: "9780156012195",
			estimatedReadingTime: "1h 30min",
			isAvailable: true,
		},
		{
			id: 10,
			title: "The Secret Garden",
			author: "Frances Hodgson Burnett",
			description:
				"Sierota odkrywa zamknięty ogród i stopniowo odmienia swoje życie, przywracając zapomniane miejsce do życia.",
			pages: 331,
			genre: "Children's Fiction",
			year: 1911,
			language: "English",
			cover: "/books/secret-garden.jpg",
			rating: 4.3,
			isbn: "9780142437054",
			estimatedReadingTime: "5h 40min",
			isAvailable: true,
		},
	],

	[
		{
			id: 11,
			title: "Pride and Prejudice",
			author: "Jane Austen",
			description:
				"Elizabeth Bennet mierzy się z oczekiwaniami rodziny, normami społecznymi i skomplikowaną relacją z bogatym panem Darcym.",
			pages: 432,
			genre: "Classic Romance",
			year: 1813,
			language: "English",
			cover: "/books/pride-and-prejudice.jpg",
			rating: 4.7,
			isbn: "9780141439518",
			estimatedReadingTime: "7h 30min",
			isAvailable: true,
		},
		{
			id: 12,
			title: "Dracula",
			author: "Bram Stoker",
			description:
				"Młody prawnik podróżuje do Transylwanii i zostaje uwikłany w przerażające plany hrabiego Drakuli.",
			pages: 418,
			genre: "Horror",
			year: 1897,
			language: "English",
			cover: "/books/dracula.jpg",
			rating: 4.5,
			isbn: "9780141439846",
			estimatedReadingTime: "7h 10min",
			isAvailable: true,
		},
		{
			id: 13,
			title: "Jane Eyre",
			author: "Charlotte Brontë",
			description:
				"Sierota dorasta, stając się niezależną kobietą, której poszukiwanie miłości i własnego miejsca prowadzi ją do tajemniczej posiadłości.",
			pages: 532,
			genre: "Classic Romance",
			year: 1847,
			language: "English",
			cover: "/books/jane-eyre.jpg",
			rating: 4.6,
			isbn: "9780141441146",
			estimatedReadingTime: "9h 15min",
			isAvailable: true,
		},
		{
			id: 14,
			title: "Moby-Dick",
			author: "Herman Melville",
			description:
				"Kapitan Ahab staje się obsesyjnie pochłonięty polowaniem na ogromnego białego wieloryba, który niegdyś zniszczył jego statek.",
			pages: 720,
			genre: "Adventure",
			year: 1851,
			language: "English",
			cover: "/books/moby-dick.jpg",
			rating: 4.1,
			isbn: "9780142437247",
			estimatedReadingTime: "12h 30min",
			isAvailable: true,
		},
		{
			id: 15,
			title: "The Time Machine",
			author: "H. G. Wells",
			description:
				"Wynalazca podróżuje w odległą przyszłość i odkrywa radykalnie odmieniony świat ludzkości.",
			pages: 118,
			genre: "Science Fiction",
			year: 1895,
			language: "English",
			cover: "/books/time-machine.jpg",
			rating: 4.2,
			isbn: "9780141439976",
			estimatedReadingTime: "2h",
			isAvailable: true,
		},
		{
			id: 16,
			title: "The Odyssey",
			author: "Homer",
			description:
				"Odyseusz próbuje wrócić do domu po wojnie trojańskiej, napotykając po drodze bogów, potwory i niezliczone niebezpieczeństwa.",
			pages: 541,
			genre: "Epic",
			year: -700,
			language: "English",
			cover: "/books/odyssey.jpg",
			rating: 4.4,
			isbn: "9780140268867",
			estimatedReadingTime: "9h 30min",
			isAvailable: true,
		},
		{
			id: 17,
			title: "The Metamorphosis",
			author: "Franz Kafka",
			description:
				"Gregor Samsa budzi się pewnego ranka i odkrywa, że w tajemniczy sposób przemienił się w potwornego owada.",
			pages: 96,
			genre: "Absurdist Fiction",
			year: 1915,
			language: "English",
			cover: "/books/metamorphosis.jpg",
			rating: 4.5,
			isbn: "9780553213690",
			estimatedReadingTime: "1h 40min",
			isAvailable: true,
		},
		{
			id: 18,
			title: "The Great Gatsby",
			author: "F. Scott Fitzgerald",
			description:
				"Tajemniczy milioner urządza wystawne przyjęcia, skrywając obsesyjne pragnienie odzyskania utraconej miłości.",
			pages: 180,
			genre: "Classic Fiction",
			year: 1925,
			language: "English",
			cover: "/books/great-gatsby.jpg",
			rating: 4.4,
			isbn: "9780743273565",
			estimatedReadingTime: "3h",
			isAvailable: true,
		},
		{
			id: 19,
			title: "Alice's Adventures in Wonderland",
			author: "Lewis Carroll",
			description:
				"Alicja wpada do króliczej nory i trafia do dziwnego świata, w którym logika, język i tożsamość nieustannie się zmieniają.",
			pages: 192,
			genre: "Fantasy",
			year: 1865,
			language: "English",
			cover: "/books/alice.jpg",
			rating: 4.6,
			isbn: "9780141439761",
			estimatedReadingTime: "3h 20min",
			isAvailable: true,
		},
		{
			id: 20,
			title: "The War of the Worlds",
			author: "H. G. Wells",
			description:
				"Ziemia zostaje zaatakowana przez technologicznie zaawansowane istoty z Marsa, zmuszając ludzkość do walki o przetrwanie.",
			pages: 192,
			genre: "Science Fiction",
			year: 1898,
			language: "English",
			cover: "/books/war-of-the-worlds.jpg",
			rating: 4.2,
			isbn: "9780141441030",
			estimatedReadingTime: "3h 15min",
			isAvailable: true,
		},
	],

	[
		{
			id: 21,
			title: "Crime and Punishment",
			author: "Fyodor Dostoevsky",
			description:
				"Biedny student popełnia morderstwo i zmaga się z poczuciem winy, moralnością oraz konsekwencjami swojego czynu.",
			pages: 671,
			genre: "Psychological Fiction",
			year: 1866,
			language: "English",
			cover: "/books/crime-and-punishment.jpg",
			rating: 4.7,
			isbn: "9780140449136",
			estimatedReadingTime: "11h 40min",
			isAvailable: true,
		},
		{
			id: 22,
			title: "The Brothers Karamazov",
			author: "Fyodor Dostoevsky",
			description:
				"Trzej bracia o skrajnie różnych osobowościach zostają uwikłani w rodzinny konflikt dotyczący wiary, moralności i morderstwa.",
			pages: 796,
			genre: "Philosophical Fiction",
			year: 1880,
			language: "English",
			cover: "/books/brothers-karamazov.jpg",
			rating: 4.8,
			isbn: "9780374528379",
			estimatedReadingTime: "14h",
			isAvailable: true,
		},
		{
			id: 23,
			title: "The Trial",
			author: "Franz Kafka",
			description:
				"Mężczyzna zostaje aresztowany bez informacji o popełnionej zbrodni i zostaje uwięziony w niezrozumiałym systemie prawnym.",
			pages: 255,
			genre: "Absurdist Fiction",
			year: 1925,
			language: "English",
			cover: "/books/the-trial.jpg",
			rating: 4.3,
			isbn: "9780805209990",
			estimatedReadingTime: "4h 20min",
			isAvailable: true,
		},
		{
			id: 24,
			title: "One Hundred Years of Solitude",
			author: "Gabriel García Márquez",
			description:
				"Historia rodziny Buendía rozgrywa się na przestrzeni kilku pokoleń w fikcyjnym miasteczku Macondo.",
			pages: 417,
			genre: "Magical Realism",
			year: 1967,
			language: "English",
			cover: "/books/one-hundred-years.jpg",
			rating: 4.7,
			isbn: "9780060883287",
			estimatedReadingTime: "7h 20min",
			isAvailable: true,
		},
		{
			id: 25,
			title: "The Stranger",
			author: "Albert Camus",
			description:
				"Emocjonalnie obojętny mężczyzna zostaje uwikłany w bezsensowny akt przemocy i konfrontuje się z obojętnym światem.",
			pages: 123,
			genre: "Philosophical Fiction",
			year: 1942,
			language: "English",
			cover: "/books/the-stranger.jpg",
			rating: 4.5,
			isbn: "9780679720201",
			estimatedReadingTime: "2h 10min",
			isAvailable: true,
		},
		{
			id: 26,
			title: "The Old Man and the Sea",
			author: "Ernest Hemingway",
			description:
				"Starszy rybak wypływa daleko w morze, podejmując ostatnią próbę udowodnienia swojej wartości.",
			pages: 127,
			genre: "Literary Fiction",
			year: 1952,
			language: "English",
			cover: "/books/old-man-and-sea.jpg",
			rating: 4.5,
			isbn: "9780684837387",
			estimatedReadingTime: "2h 15min",
			isAvailable: true,
		},
		{
			id: 27,
			title: "The Count of Monte Cristo",
			author: "Alexandre Dumas",
			description:
				"Po latach uwięzienia spowodowanego zdradą Edmond Dantès ucieka i powraca pod nową tożsamością, aby dokonać zemsty.",
			pages: 1276,
			genre: "Adventure",
			year: 1844,
			language: "English",
			cover: "/books/monte-cristo.jpg",
			rating: 4.8,
			isbn: "9780140449266",
			estimatedReadingTime: "22h",
			isAvailable: true,
		},
		{
			id: 28,
			title: "Les Misérables",
			author: "Victor Hugo",
			description:
				"Jean Valjean próbuje odbudować swoje życie, będąc nieustannie ściganym przez bezwzględnego inspektora policji.",
			pages: 1463,
			genre: "Historical Fiction",
			year: 1862,
			language: "English",
			cover: "/books/les-miserables.jpg",
			rating: 4.7,
			isbn: "9780451419439",
			estimatedReadingTime: "25h",
			isAvailable: true,
		},
		{
			id: 29,
			title: "The Adventures of Sherlock Holmes",
			author: "Arthur Conan Doyle",
			description:
				"Sherlock Holmes wykorzystuje obserwację i dedukcję, aby rozwiązywać serię niezwykłych zagadek.",
			pages: 307,
			genre: "Detective Fiction",
			year: 1892,
			language: "English",
			cover: "/books/sherlock-holmes.jpg",
			rating: 4.6,
			isbn: "9780140439076",
			estimatedReadingTime: "5h 20min",
			isAvailable: true,
		},
		{
			id: 30,
			title: "The Invisible Man",
			author: "H. G. Wells",
			description:
				"Naukowiec odkrywa sposób na stanie się niewidzialnym, ale szybko przekonuje się, że jego odkrycie niesie ze sobą przerażające konsekwencje.",
			pages: 162,
			genre: "Science Fiction",
			year: 1897,
			language: "English",
			cover: "/books/invisible-man.jpg",
			rating: 4.2,
			isbn: "9780141439982",
			estimatedReadingTime: "2h 45min",
			isAvailable: true,
		},
	],

	[
		{
			id: 31,
			title: "Wuthering Heights",
			author: "Emily Brontë",
			description:
				"Namiętna i destrukcyjna relacja rozwija się na tle ponurego krajobrazu wrzosowisk Yorkshire.",
			pages: 416,
			genre: "Gothic Romance",
			year: 1847,
			language: "English",
			cover: "/books/wuthering-heights.jpg",
			rating: 4.4,
			isbn: "9780141439556",
			estimatedReadingTime: "7h 10min",
			isAvailable: true,
		},
		{
			id: 32,
			title: "Great Expectations",
			author: "Charles Dickens",
			description:
				"Osierocony chłopiec niespodziewanie otrzymuje finansowe wsparcie i rozpoczyna nowe życie pełne ambicji, miłości i tajemnic.",
			pages: 505,
			genre: "Classic Fiction",
			year: 1861,
			language: "English",
			cover: "/books/great-expectations.jpg",
			rating: 4.5,
			isbn: "9780141439563",
			estimatedReadingTime: "8h 40min",
			isAvailable: true,
		},
		{
			id: 33,
			title: "The Picture of Dorian Gray",
			author: "Oscar Wilde",
			description:
				"Młody mężczyzna pozostaje wiecznie piękny, podczas gdy tajemniczy portret nosi ślady jego moralnego upadku.",
			pages: 254,
			genre: "Gothic Fiction",
			year: 1890,
			language: "English",
			cover: "/books/dorian-gray-2.jpg",
			rating: 4.5,
			isbn: "9780141439570",
			estimatedReadingTime: "4h 30min",
			isAvailable: true,
		},
		{
			id: 34,
			title: "The Call of the Wild",
			author: "Jack London",
			description:
				"Udomowiony pies zostaje zmuszony do życia w surowym świecie Jukonu, gdzie instynkt i przetrwanie stają się kluczowe.",
			pages: 172,
			genre: "Adventure",
			year: 1903,
			language: "English",
			cover: "/books/call-of-the-wild.jpg",
			rating: 4.4,
			isbn: "9780141321059",
			estimatedReadingTime: "3h",
			isAvailable: true,
		},
		{
			id: 35,
			title: "Treasure Island",
			author: "Robert Louis Stevenson",
			description:
				"Młody chłopiec wyrusza na niebezpieczną wyprawę w poszukiwaniu ukrytego skarbu i spotyka legendarnego Long Johna Silvera.",
			pages: 240,
			genre: "Adventure",
			year: 1883,
			language: "English",
			cover: "/books/treasure-island.jpg",
			rating: 4.5,
			isbn: "9780141321004",
			estimatedReadingTime: "4h",
			isAvailable: true,
		},
		{
			id: 36,
			title: "Around the World in Eighty Days",
			author: "Jules Verne",
			description:
				"Phileas Fogg zakłada się, że zdoła okrążyć świat w ciągu osiemdziesięciu dni.",
			pages: 272,
			genre: "Adventure",
			year: 1872,
			language: "English",
			cover: "/books/around-the-world.jpg",
			rating: 4.4,
			isbn: "9780140449068",
			estimatedReadingTime: "4h 40min",
			isAvailable: true,
		},
		{
			id: 37,
			title: "The Wonderful Wizard of Oz",
			author: "L. Frank Baum",
			description:
				"Dorota zostaje przeniesiona do magicznej krainy, gdzie wraz z trzema niezwykłymi towarzyszami podąża Bursztynową Drogą.",
			pages: 176,
			genre: "Fantasy",
			year: 1900,
			language: "English",
			cover: "/books/wizard-of-oz.jpg",
			rating: 4.5,
			isbn: "9780142437223",
			estimatedReadingTime: "3h",
			isAvailable: true,
		},
		{
			id: 38,
			title: "The Wind in the Willows",
			author: "Kenneth Grahame",
			description:
				"Czwórka zwierzęcych przyjaciół przeżywa przygody nad rzeką, ucząc się o przyjaźni, domu i wolności.",
			pages: 256,
			genre: "Children's Fiction",
			year: 1908,
			language: "English",
			cover: "/books/wind-in-the-willows.jpg",
			rating: 4.3,
			isbn: "9780141437339",
			estimatedReadingTime: "4h 20min",
			isAvailable: true,
		},
		{
			id: 39,
			title: "The Jungle Book",
			author: "Rudyard Kipling",
			description:
				"Mowgli dorasta wśród wilków w indyjskiej dżungli, ucząc się jej praw od otaczających go zwierząt.",
			pages: 256,
			genre: "Adventure",
			year: 1894,
			language: "English",
			cover: "/books/jungle-book.jpg",
			rating: 4.4,
			isbn: "9780141321011",
			estimatedReadingTime: "4h 15min",
			isAvailable: true,
		},
		{
			id: 40,
			title: "The Wonderful Life",
			author: "Example Author",
			description:
				"Fikcyjna książka przykładowa służąca do zaprezentowania struktury biblioteki Archetyp.",
			pages: 300,
			genre: "Fiction",
			year: 2020,
			language: "English",
			cover: "/books/example.jpg",
			rating: 4.0,
			isbn: "0000000000000",
			estimatedReadingTime: "5h",
			isAvailable: true,
		},
	],

	[
		{
			id: 41,
			title: "The Great Gatsby",
			author: "F. Scott Fitzgerald",
			description:
				"Wystawne życie tajemniczego milionera skrywa jego obsesyjne pragnienie odzyskania utraconej miłości.",
			pages: 180,
			genre: "Classic Fiction",
			year: 1925,
			language: "English",
			cover: "/books/gatsby-2.jpg",
			rating: 4.4,
			isbn: "9780743273565",
			estimatedReadingTime: "3h",
			isAvailable: true,
		},
		{
			id: 42,
			title: "The Hobbit",
			author: "J. R. R. Tolkien",
			description:
				"Bilbo Baggins opuszcza spokojny dom i dołącza do niebezpiecznej wyprawy mającej na celu odzyskanie utraconego królestwa krasnoludów.",
			pages: 310,
			genre: "Fantasy",
			year: 1937,
			language: "English",
			cover: "/books/hobbit.jpg",
			rating: 4.8,
			isbn: "9780547928227",
			estimatedReadingTime: "5h 30min",
			isAvailable: true,
		},
		{
			id: 43,
			title: "The Fellowship of the Ring",
			author: "J. R. R. Tolkien",
			description:
				"Młody hobbit rozpoczyna niebezpieczną podróż, aby zniszczyć potężny pierścień, zanim jego twórca zdoła go odzyskać.",
			pages: 423,
			genre: "Fantasy",
			year: 1954,
			language: "English",
			cover: "/books/fellowship.jpg",
			rating: 4.9,
			isbn: "9780544003415",
			estimatedReadingTime: "8h",
			isAvailable: true,
		},
		{
			id: 44,
			title: "The Martian",
			author: "Andy Weir",
			description:
				"Samotny astronauta uwięziony na Marsie musi wykorzystać naukę, inżynierię i własną pomysłowość, aby przetrwać.",
			pages: 369,
			genre: "Science Fiction",
			year: 2011,
			language: "English",
			cover: "/books/martian.jpg",
			rating: 4.7,
			isbn: "9780804139021",
			estimatedReadingTime: "6h 20min",
			isAvailable: true,
		},
		{
			id: 45,
			title: "The Road",
			author: "Cormac McCarthy",
			description:
				"Ojciec i syn przemierzają zniszczony świat, próbując przetrwać i jednocześnie zachować swoje człowieczeństwo.",
			pages: 287,
			genre: "Post-Apocalyptic",
			year: 2006,
			language: "English",
			cover: "/books/the-road.jpg",
			rating: 4.5,
			isbn: "9780307386458",
			estimatedReadingTime: "4h 50min",
			isAvailable: true,
		},
		{
			id: 46,
			title: "The Alchemist",
			author: "Paulo Coelho",
			description:
				"Młody pasterz wyrusza w podróż w poszukiwaniu ukrytego skarbu i odkrywa głębsze znaczenie swojej drogi.",
			pages: 208,
			genre: "Philosophical Fiction",
			year: 1988,
			language: "English",
			cover: "/books/alchemist.jpg",
			rating: 4.4,
			isbn: "9780062315007",
			estimatedReadingTime: "3h 30min",
			isAvailable: true,
		},
		{
			id: 47,
			title: "The Midnight Library",
			author: "Matt Haig",
			description:
				"Między życiem a śmiercią znajduje się tajemnicza biblioteka zawierająca nieskończoną liczbę możliwych wersji życia jednej osoby.",
			pages: 304,
			genre: "Contemporary Fiction",
			year: 2020,
			language: "English",
			cover: "/books/midnight-library.jpg",
			rating: 4.3,
			isbn: "9780525559474",
			estimatedReadingTime: "5h 10min",
			isAvailable: true,
		},
		{
			id: 48,
			title: "Siddhartha",
			author: "Hermann Hesse",
			description:
				"Młody mężczyzna opuszcza znany sobie świat i poszukuje mądrości, podążając różnymi ścieżkami życia.",
			pages: 152,
			genre: "Philosophical Fiction",
			year: 1922,
			language: "English",
			cover: "/books/siddhartha.jpg",
			rating: 4.5,
			isbn: "9780553208849",
			estimatedReadingTime: "2h 40min",
			isAvailable: true,
		},
		{
			id: 49,
			title: "The Plague",
			author: "Albert Camus",
			description:
				"Śmiertelna epidemia odcina miasto od świata i zmusza jego mieszkańców do zmierzenia się z cierpieniem, solidarnością i sensem oporu.",
			pages: 308,
			genre: "Philosophical Fiction",
			year: 1947,
			language: "English",
			cover: "/books/the-plague.jpg",
			rating: 4.5,
			isbn: "9780679720218",
			estimatedReadingTime: "5h 20min",
			isAvailable: true,
		},
		{
			id: 50,
			title: "Twenty Thousand Leagues Under the Sea",
			author: "Jules Verne",
			description:
				"Wyprawa morska zamienia się w podróż na pokładzie tajemniczej łodzi podwodnej Nautilus dowodzonej przez kapitana Nemo.",
			pages: 432,
			genre: "Adventure",
			year: 1870,
			language: "English",
			cover: "/books/twenty-thousand-leagues.jpg",
			rating: 4.4,
			isbn: "9780140448191",
			estimatedReadingTime: "7h 30min",
			isAvailable: true,
		},
	],
];
