import type { Metadata } from "next";
import { Playfair_Display, Montserrat } from "next/font/google";
import "@/app/globals.css";

const playfairDisplay = Playfair_Display({
	variable: "--font-playfairDisplay",
	subsets: ["latin"],
});
const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Archetyp | Czytelnia",
	description: "Generated by create next app",
};

// Musi być zsynchronizowane ręcznie z ThemeData/changeTheme w lib/themes.ts —
// to zwykły string JS wykonywany zanim cokolwiek się wyrenderuje, więc nie może
// importować kodu z modułów aplikacji.
const themeInitScript = `
(function () {
	try {
		const raw = localStorage.getItem("themeData");
		if (!raw) return;
		const data = JSON.parse(raw);
		if (!data || typeof data !== "object") return;
		for (var key in data) {
			if (key === "name") continue;
			document.documentElement.style.setProperty(key, data[key]);
		}
	} catch (e) {}
})();
`;

export default function DashboardLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={`${montserrat.variable} ${playfairDisplay.variable} h-full antialiased scroll-smooth`}>
			<head>
				<script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
			</head>
			<body className="bg-main h-dvh overflow-hidden">{children}</body>
		</html>
	);
}
